export const FEEDBACK_CATEGORIES = [
  { id: "teacher", label: "Teacher & Faculty", icon: "GraduationCap", desc: "Teaching quality and behavior" },
  { id: "mess", label: "Mess & Food", icon: "UtensilsCrossed", desc: "Food quality, hygiene, and pricing" },
  { id: "hostel", label: "Hostel & Living", icon: "Home", desc: "Room maintenance and facilities" },
  { id: "infrastructure", label: "College Infrastructure", icon: "Building2", desc: "Classrooms, washrooms, ACs, projectors" },
  { id: "lab", label: "Lab & Equipments", icon: "FlaskConical", desc: "Computers, software, hardware tools" },
  { id: "practical", label: "Practical & Viva", icon: "Microscope", desc: "Lab sessions and internal assessments" },
  { id: "management", label: "Administration & Management", icon: "Users", desc: "Staff behavior and college rules" },
  { id: "fee", label: "Fee Issue", icon: "CreditCard", desc: "Fines, fee payment portal, dues" },
  { id: "paper", label: "Paper & Exams", icon: "FileText", desc: "Exam schedule, checking, results" },
  { id: "placement", label: "Placement Issue", icon: "Briefcase", desc: "Company drives, training, support" },
  { id: "attendance", label: "Attendance & Leaves", icon: "Calendar", desc: "Medical leaves, attendance criteria" },
  { id: "environment", label: "College Environment", icon: "Leaf", desc: "Safety, ragging, campus culture" },
]

export const FACULTY_FEEDBACK_CATEGORIES = [
  { id: "hr", label: "HR & Management", icon: "Users", desc: "Salary, leaves, administrative support" },
  { id: "research", label: "Research Facilities", icon: "Microscope", desc: "Grants, lab access, publications support" },
  { id: "work_environment", label: "Work Environment", icon: "Briefcase", desc: "Workload, schedule, peer relations" },
  { id: "infrastructure", label: "Faculty Infrastructure", icon: "Building", desc: "Staff rooms, computing hardware, Wi-Fi" },
  { id: "general", label: "General Feedback", icon: "MessageSquare", desc: "Overall experience and suggestions" },
]

export const COURSES = [
  "B.Tech",
  "M.Tech",
  "B.Pharm",
  "M.Pharm",
  "MBA",
  "MCA",
  "B.Arch",
  "BHMCT",
]

export const DEPARTMENTS = [
  "Computer Science & Engineering",
  "Information Technology",
  "Electronics & Communication",
  "Mechanical Engineering",
  "Civil Engineering",
  "Electrical & Electronics",
  "Business Administration (MBA)",
  "Applied Sciences & Humanities",
]

export const YEARS_OF_STUDY = [
  "1st Year",
  "2nd Year",
  "3rd Year",
  "4th Year",
  "Postgraduate",
  "Alumni",
]

export const AKTU_COLLEGES = [
  "BRD Medical College, Gorakhpur",
  "A.N.A Institute of Pharmaceutical Sciences & Research, Bareilly",
  "A.N.A. College of Engineering & Management, Bareilly",
  "ABES Engineering College, Ghaziabad",
  "ABES Institute of Technology, Ghaziabad",
  "ABSS Institute of Technology, Mawana Road, Meerut",
  "ACE College of Engineering & Management, Etmadpura, Agra",
  "ACN College of Engineering & Management Studies, Kasimpur Road, VIll.- Cherrat, Aligarh",
  "ADVANCE COLLEGE OF EDUCATION, Kanpur",
  "AKS Management College, Bakshi-Ka-Talab, Lucknow",
  "ANA College of Management Studies, Bareilly",
  "APS College of Education & Technology, Meerut",
  "APS College of Education, Meerut",
  "AR Institute of Management & Technology, Meerut",
  "AUROUS INSTITUTE OF MANAGEMENT, Barabanki",
  "AXIS INSTITUTE OF PHARMACY, Kanpur",
  "Aashlar Business School, Mahuan, Near Toll Plaza, Mathura",
  "Abhay Memorial Trust Group of Institutions, Allahabad",
  "Accurate Institute of Advanced Management, Greater Noida",
  "Accurate Institute of Architercture & Panning, Greater Noida",
  "Accurate Institute of Management and Technology, Greater Noida",
  "Acharya Narendra Dev College of Pharmacy, Gonda",
  "Adhunik College of Engineering, Duhai, Ghaziabad",
  "Adhunik Institute of Productivity Management and Research, Ghaziabad",
  "Advanced Institute of Bio-Tech & Paramedical Sciences, Kanpur",
  "Agra Public College of Technology & Management",
  "Agra Public Institute of Technology & Computer Education, Artoni",
  "Agra Vansthali Mahavidyalaya",
  "Ajay Kumar Garg Engineering College, Ghaziabad",
  "Ajay Kumar Garg Institute of Management, Ghaziabad",
  "Al Barkat Institute of Management Studies, Aligarh",
  "Aligarh College of Engineering & Technology",
  "Aligarh College of Pharmacy",
  "Allenhouse Institute of Technology, Kanpur",
  "Amani Group of Institutions, Amroha",
  "Ambalika Institute of Management & Technology, Lucknow",
  "Anand College of Pharmacy, Agra",
  "Anand Engineering College, Artoni, Agra",
  "Anand college of Architecture, Agra",
  "Anjali College of Pharmacy & Science Etmadpur, Agra",
  "Apeejay Institute of Technology, School of Architecture & Planning, Greater Noida",
  "Apex Institute of Pharmacy, Mirzapur",
  "Apex Institute of Technology, Rampur",
  "Apollo Institute of Technology, Kanpur",
  "Aryakul College of Management, Lucknow",
  "Aryakul College of Pharmacy & Research, Lucknow",
  "Aryan Institute of Technology, Jindal Nagar, Ghaziabad",
  "Aryavart Institute of Technology & Management, Lucknow",
  "Ashoka Institute of Technology & Management, Varanasi",
  "Asian Institute of Management & Higher Studies, Kanpur",
  "Axis Business School, Kanpur",
  "Axis Institute of Architecture, Kanpur",
  "Axis Institute of Fashion Technology, Kanpur",
  "Axis Institute of Planning and Management, Kanpur",
  "Axis Institute of Technology & Management, Kanpur",
  "Azad Institute of Engineering & Technology, Lucknow",
  "Azad Institute of Pharmacy & Research, Lucknow",
  "B.B.D National Institute of Tech. & Management, Lucknow",
  "B.B.S. Institute of Pharmaceutical & Allied Science, Greater Noida",
  "B.B.S.College of Engineering and Technology, Allahabad",
  "B.N.College of Engineering & Technology, Lucknow",
  "B.S.A. College of Engineering & Technology, Mathura",
  "BBDIT COLLEGE OF PHARMACY, Ghaziabad",
  "BIMT College, Meerut",
  "Babu Banarasi Das Engineering College, Lucknow",
  "Babu Banarasi Das Institute of Technology, Duhai, Ghaziabad",
  "Babu Banarasi Das National Institute of Technology & Management, Lucknow",
  "Babu Banarasi Das Northern India Institute of Technology, Lucknow",
  "Babu Banarsi Das Institute of Engineering Technology & Research Centre, Bulandshahr",
  "Babu Sundar Singh Institute of Technology & Management, Lucknow",
  "Bansal Institute of Engineering & Technology, Lucknow",
  "Banshi College of Management & Technology, Kanpur",
  "Basudev Institute of Management & Technology, Lucknow",
  "Bhabha College of Engineering, Kanpur Dehat",
  "Bhabha Institute of Technology, Kanpur Dehat",
  "Bhagwant Institute of Pharmacy, Muzaffarnagar",
  "Bhagwant Institute of Technology, Ghaziabad",
  "Bhagwant Institute of Technology, Muzaffarnagar",
  "Bhagwati Institute of Technology and Science, Masuri, Ghaziabad",
  "Bhalchandra Institute of Education & Management, Lucknow",
  "Bharat Institute of Technology (MBA Institute), Meerut",
  "Bharat Institute of Technology, Meerut",
  "Bharti Institute of Management & Technology, Kila Road, Rali Chauhan, Meerut",
  "Bhavdiya Institute of Business Management, Faizabad",
  "Bhavdiya Institute of Pharmaceutical Sciences and Research, Faizabad",
  "Bora Institute of Management Science, Lucknow",
  "Brahmanand  Institute of Research Technology & Management, Bulandshahr",
  "Brahmanand Group of Institutions, Bulandshahr",
  "Buddha Institute of Technology, Gorakhpur",
  "Bundelkhand Institute of Engineering & Technology, Jhansi",
  "CBS College of Management, Agra",
  "Central Institute of Management & Technology, Lucknow",
  "Central Institute of Plastic Engineering & Technology, Lucknow",
  "Centre for Advance Studies, Lucknow",
  "Ch. Charan Singh College of Pharmacy, Greater Noida",
  "Ch. Harchand Singh College of Management, Khurja",
  "Chandra Mauli Institute of Management Sciences & Technology, Gorakhpur",
  "Chandra Shekhar Singh College of Pharmacy, Kaushambi",
  "Chatrapati Shahu Ji Maharaj College of Engineering and Technology, Allahabad",
  "Chaudhary Beeri Singh College of Engineering & Management, Near Peeli Pokhar, Teh.- Etmadpur, Agra",
  "City College of Management & Technology, Lucknow",
  "College of Business Studies, Sikandara, Agra",
  "College of Engineering & Rural Technology, Meerut",
  "College of Engineering, Science & Technology, Lucknow",
  "College of Management Studies, Kanpur",
  "College of Pharmacy, Jakhoda, Agra",
  "College of Pharmacy, Varanasi",
  "D.J. College of Pharmacy, Modinagar",
  "D.J.College of Engineering & Technology, Modinagar",
  "D.N. College, Bulandshahr",
  "DNM Institute of Engineering & Technology, Lucknow",
  "DNS College of Engineering & Technology, Didoli, Amroha",
  "DR. VIRENDRA SWARUP MEMORIAL TRUST GROUP OF INSTITUIONS , KANPUR NAGAR, Kanpur",
  "Dayal Group of Institutions, Lucknow",
  "Dayanad Deena Nath College of Management, Kanpur",
  "Dayanand Academy of Management Studies, Kanpur",
  "Dayanand Dinanath College, Institute of Pharmacy, Kanpur",
  "Dayanand Vidhyapeeth Education, Meerut",
  "Deewan V.S. Institute of Engineering & Technology, Meerut",
  "Delhi Institute of Engineering and Technology, Meerut",
  "Dev Bhoomi Groups of Institutions, Faculty of Computer Application, Saharanpur",
  "Dev Bhoomi Groups of Institutions, Faculty of Management, Saharanpur",
  "Dev Bhoomi Groups of Institutions, Saharanpur",
  "Devender Singh Institute of Technology & Management, Ghaziabad",
  "Devidayal Memorial Institutions, Kanpur Dehat",
  "Devprayag Institute of Management, Allahabad",
  "Devrishi Institute of Management & Technology, Saharanpur",
  "Dewan Institute of Management Studies, Meerut",
  "Dewan V.S. Institute of Hotel Management & Technology, Meerut",
  "Disha Bharti College of Management & Education, Saharanpur",
  "Disha Institute of Science & Technology, Dhampur",
  "Divya College of Pharmacy, Mathura",
  "Doodhnath College of Pharmacy, Jhansi",
  "Doon College of Education, Saharanpur",
  "Doon College of Engg. & Technology, Saharanpur",
  "Dr Virendra Swaroop Institute of Professional Studies, Kanpur",
  "Dr Virendra Swarup Memorial Trust Group of Institutions, Unnao",
  "Dr. Ambedkar Institute of Technology For Handicapped, Kanpur",
  "Dr. B.R. Ambedkar Pooja College of Pharmacy, Gorakhpur",
  "Dr. K.N. Modi Institute of Pharmaceutical Science & Research, Modinagar",
  "Dr. K.N.Modi institute of Engineering & Technology, Modinagar",
  "Dr. M.C. Saxena College of Engineering & Technology, Lucknow",
  "Dr. M.C.Saxena College of Pharmacy, Lucknow",
  "Dr. Om Prakash Institute of Management & Technology, Farrukhabad",
  "Dr. Om Prakash School Of Pharmacy, Farrukhabad",
  "Dr. Ram Manohar Lohia College of Pharmacy, Modinagar",
  "Dr. Ram Manohar Lohia Institute, Modinagar",
  "Dr. Rizvi College of Engineering, Karari, Kaushambi",
  "Dr. Virendra Swarup Institute of Computer Studies, Kanpur",
  "Dronacharya Group of Institutions, Greater Noida",
  "Dushyant college of pharmacy, Firozabad",
  "Dwarikadheesh Research Education & Management School, Saharanpur",
  "Edify Institute of Management & Technology, Mathura",
  "Eshan College of Management, Mathura",
  "Eshan group of Institute, Mathura",
  "Ewing Christian Institute of Management & Technology, Allahabad",
  "F I PHARMACY COLLEGE, Lucknow",
  "FIT Engineering College, Kaseru Buxar, Meerut",
  "FMG Academy Group of Institutions, Greater Noida",
  "Faculty of Architecture, AKTU(Formerly: Lucknow College of Architecture & GCA)",
  "Faculty of Engineering & Technology, Agra College",
  "Faculty of Engineering, Shanti Niketan Trust's Group of Institutions, Mohiuddinpur, Meerut",
  "Faculty of Management and Technology, Varanasi",
  "Faculty of Management, CSM Group of Institutions, Allahabad",
  "Faculty of Management, Jhunjhunwala Degree College, Faizabad",
  "Feroze Gandhi Institute of Engineering & Technology, Raebareli",
  "Forte Institute of Technology, Meerut",
  "Forth Dimension College of Architecture, Saharanpur",
  "Future Institute of Engineering & Technology, Bareilly",
  "Future Institute of Management and Technology, Bareilly",
  "Future Institute of Pharmacy, Bareilly",
  "G & R Institute of Management and Technology, Bulandshahr",
  "G.C.R.G. Memorial Trust's Group of Institutions, Faculty of Engineering, Lucknow",
  "G.L Bajaj Institute of Management and Research, Greater Noida",
  "G.L. Bajaj Group of Institutions, Mathura Delhi Highway",
  "GCRG COLLEGE OF PHARMACY, Lucknow",
  "GCRG Memorial Trust's Group of Institutions, Faculty of Management, Lucknow",
  "GL Bajaj Institute of Technology and Management, Greater Noida",
  "GSRM MEMORIAL COLLEGE OF PHARMACY, Lucknow",
  "Galgotias College of Engineering and Technology, Greater Noida",
  "Galgotias Institute of Management & Technology, Greater Noida",
  "Gauri Vidya Peeth Business School, Meerut",
  "Ghanshyam Binani Academy of Management Sciences, Mirzapur",
  "Global Institute of Information Technology, Greater Noida",
  "Goel Institute of Higher Studies, Lucknow",
  "Goel Institute of Pharmacy & Sciences, Lucknow",
  "Goel Institute of Technology & Management, Lucknow",
  "Gokaran Narvadeshwar Institute of Technology & Management, Barabanki",
  "Greater Noida College of Technology",
  "Greater Noida Institute of Business Management",
  "Greater Noida Institute of Technology",
  "Greater Noida Institute of Technology (MBA Institute)",
  "Gyan Bharti Institute of Technology, Partapur Bypass Road, Meerut",
  "H.I.M.T. College of Pharmacy, Greater Noida",
  "H.M.F.A.Memorial Institute of Engineering & Technology, Allahabad",
  "H.R. Institute of Hotel Management, Morta, Ghaziabad",
  "H.R. Institute of Pharmacy, Morta, Ghaziabad",
  "H.R. Institute of Technology, Morta, Ghaziabad",
  "HLM College, 11 km. Delhi-Meerut Road, Ghaziabad",
  "HYGIA INSTITUTE OF PHARMACY, Lucknow",
  "Hardayal Technical Campus, Mathura",
  "Hari College of Management, Gagalheri, Saharanpur",
  "Harlal Institute of Management & Technology, Greater Noida",
  "Heeralal Yadav Institute of Technology & Management, Lucknow",
  "Heritage Institute of Hotel & Tourism, Agra",
  "Hi-Tech Institute of Engineering & Technology, Ghaziabad",
  "Hierank Business School, Noida",
  "Hillwood Medical School, Bulandshahr",
  "Himalayan Institute of Technology & Management, Lucknow",
  "Hindustan College of Science and Technology, Mathura",
  "Hindustan Institute of Management & Computer Studies, Mathura",
  "Hygia College Of Pharmacy, Lucknow",
  "Hygia Institute of Pharmaceutical Education and Research, Lucknow",
  "I.I.M.T. College of Pharmacy, Greater Noida",
  "I.T.S. College of Pharmacy, Muradnagar",
  "I.T.S. Engineering College, Greater Noida",
  "IEC College of Engineering and Technology, Greater Noida",
  "IILM Academy of Highier Learning, Lucknow",
  "IILM College of Engineering and Technology, Greater Noida",
  "IIMT College of Engineering, Greater Noida",
  "IIMT Engineering College, Meerut",
  "IMS Engineering College, Ghaziabad",
  "IMS, Gajraula",
  "ISABELLA THOBURN COLLEGE, Lucknow",
  "ITERC College of Management, Ghaziabad",
  "ITM College of Pharmacy, Maharajganj",
  "ITM School of Architecture and Town Planning, Lucknow",
  "ITM School of Management, Lucknow",
  "Ibne Seena Pharmacy College, Hardoi",
  "Ideal Institute of Management and Technology, Ghaziabad",
  "Ideal Institute of Technology, Ghaziabad",
  "Indian Institute of Carpet Technology, Bhadohi",
  "Indira Gandhi Institute of Co-Operative Management, Lucknow",
  "Indraprasth Institute of Technology, Amroha",
  "Indraprastha Engineering College, Ghaziabad",
  "Indraprastha Institute of Management & Technology, Saharanpur",
  "Indus Institute of Technology & Management, Kanpur",
  "Innovative College of Pharmacy, Greater Noida",
  "Institute of Advanced Management and Research, Ghaziabad",
  "Institute of Co-Operative & Corporate Management, Research & Training, Lucknow",
  "Institute of Computer Science & Technology, Varanasi",
  "Institute of Engineering & Rural Technology, Allahabad",
  "Institute of Engineering and Technology(IET), Lucknow",
  "Institute of Engineering and Technology, Sitapur",
  "Institute of Environment & Management, Lucknow",
  "Institute of Hotel Management, Catering Technology & Applied Nutrition, Meerut",
  "Institute of Information Management & Technology, Aligarh",
  "Institute of Management & Science, Gajraula",
  "Institute of Management Education, Ghaziabad",
  "Institute of Management Research & Technology, Lucknow",
  "Institute of Management Studies, Ghaziabad",
  "Institute of Management Studies, Noida",
  "Institute of Management and Research, Ghaziabad",
  "Institute of Pharmaceutical Sciences & Research, Unnao",
  "Institute of Pharmacy, Sitapur",
  "Institute of Pharmacy, Varanasi",
  "Institute of Professional Excellence & Management, Ghaziabad",
  "Institute of Professional Studies & Research (IPSR), Unnao",
  "Institute of Technology & Management, Aligarh-Palwal-Delhi Road, Karsua",
  "Institute of Technology & Management, Gorakhpur",
  "Institute of Technology & Management, Lucknow",
  "Institute of Technology & Management, Meerut-Baghpat Road, Panchli",
  "Institute of Technology & Science, Mohan Nagar, Ghaziabad",
  "Institute of Technology and Management, Maharajganj",
  "Integrated Academy of Management & Technology{inmantec}, Ghaziabad",
  "Integrated Academy of management & Technology, Ghaziabad",
  "International Institute For Special Education (IISE), Lucknow",
  "Ishwarchand Vidyasagar Institute of Technology, Akbarpur, Mathura",
  "J P School of Business, Salarpur, Jalalpur, Rajpura, Meerut",
  "J. P. COLLEGE OF PHARMACY, Lucknow",
  "J.K. Institute of Pharmacy and Management, Khurja",
  "J.P. Institute of Engineering & Technology, Meerut",
  "J.P. Institute of Hotel Management & Catering Technology, Meerut",
  "J.S.S. Academy of Technical Education, Noida",
  "JMS Group of Institutions, Hapur",
  "JagMohan Institute of Management and Technology, Khekada, Baghpat",
  "Jagran Institute of Management, Kanpur",
  "Jahangirabad Educational Trust's Group of Institutions, Faculty of Engineering, Barabanki",
  "Jahangirabad Educational Trust's Group of Institutions, Faculty of Management, Barabanki",
  "Jaipuria institute of management, Ghaziabad",
  "Jan Kalyan Institute of Technical Excellence, Lucknow",
  "Janta College of Pharmacy, Bijnor",
  "Jeevandeep Institute of Management & Technology, Varanasi",
  "Jyoti College of Management Science and Technology, Bareilly",
  "K.P. Engineering College, Etmadpur, Agra",
  "K.R.S. College of Management, Gonda",
  "K.R.S. College of Pharmacy, Gonda",
  "K.S. Jain Institute of Engineering & Technology, Modinagar",
  "KCC Institute of Management, Greater Noida",
  "KCC Institute of Technology and Management, Greater Noida",
  "KIET School of Pharmacy, Muradnagar",
  "KIPM College of Engineering & Technology, Gorakhpur",
  "KIPM College of Management, Gorakhpur",
  "KITE Group of Institutions, KITE School of Engineering and Technology, Meerut",
  "KLS institute oF Engineering & Technology, Vill- Khudaheri, Bijnor -Hardwar Road",
  "KNGD Modi Engineering College, Modinagar",
  "KRISHNA INSTITUTE OF PHARMACY AND SCIENCES, Kanpur",
  "Kailash Institute of Pharmacy & Management, Gorakhpur",
  "Kali Charan Nigam Institute of Technology, Banda",
  "Kalka Engineering College, Partapur Bypass Road, Meerut",
  "Kalka Institute for Research & Advanced Studies, Meerut",
  "Kamal Institute of Technology, Kanpur Dehat",
  "Kamla Nehru Institute Of Physical & Social Sciences, Management Institute, Sultanpur",
  "Kamla Nehru Institute of Management & Technology, Sultanpur",
  "Kamla Nehru Institute of Physical & Social Sciences, Sultanpur",
  "Kamla Nehru Institute of Technology, Sultanpur",
  "Kanpur Institute of Management Studies, Unnao",
  "Kanpur Institute of Technology",
  "Kanpur Institute of Technology & Pharmacy",
  "Kashi Institute of Pharmacy, Varanasi",
  "Kashi Institute of Technology, Varanasi",
  "Khandelwal College of Architecture & Design, Bareilly",
  "Khandelwal College of Management Science and Technology, Bareilly",
  "Kishan Institute of Information Technology, Meerut",
  "Kothiwal Institute of Technology & Professional Studies, Pachokara Haridwar Road, Moradabad",
  "Krishna Engineering College, Ghaziabad",
  "Krishna Institute of Engineering and Technology, Muradnagar",
  "Krishna Institute of Management, Bana, Mawana Road, Meerut",
  "Krishna Institute of Technology, Kanpur",
  "Krishna Institute, Bijnor",
  "Krishna Pharmacy College, Bijnor",
  "Krishnarpit Institute of Management & Technology, Allahabad",
  "Krishnarpit Institute of Pharmacy, Allahabad",
  "Kunwar Haribansh Singh College of Pharmacy, Jaunpur",
  "Kunwar Haribansh Singh Institute of Management, Jaunpur",
  "Kunwar Satya Vira College of Engineering & Management, Bijnor",
  "LDC Institute of Technical Studies, Allahabad",
  "LTR Institute of Management, Meerut",
  "LTR Institute of Technology, Dharamsala-Bhagpat Road, Meerut",
  "Lakshya Institute of Management & Information Technology, Shahjahanpur",
  "Lakshya Technical Campus, Shahjahanpur",
  "Lal Bahadur Shastri Institute of Management & Development Studies, Lucknow",
  "Landmark Technical Campus Didauli, Amroha",
  "Late Ravindranand Baronia College of Pharmacy Mahroni, Lalitpur",
  "Lloyd Business School, Greater Noida",
  "Lloyd Institute of Management & Technology, Greater Noida",
  "Lord Krishna College of Engineering, Pilkhuwa, Hapur",
  "Lotus Institute of Management, Bareilly",
  "Lucknow Institute of Pharmacy",
  "Lucknow Institute of Technology",
  "Lucknow Model Institute of Management",
  "Lucknow Model Institute of Technology & Management",
  "Lutawan Institute of Pharmacy, Ghazipur",
  "M.C.S.College of Science And Technology, Jhansi",
  "M.G. Institute of Management & Technology, Lucknow",
  "MASS College of Engineering and Management, Hathras",
  "MIT College of Management, Moradabad",
  "Maa Bhagwata Kunwar Institute of Management, Mau",
  "Maa Gayatri College of Pharmacy  Lalitpur",
  "Maa Vaishno Devi Educational & Law College, Lucknow",
  "Madhu Vachaspati Institute of Engineering and Technology, Kaushambi",
  "Madhu Vachaspati School of Management, Kaushambi",
  "Maharaja Agrasen College of Engineering & Technology, Dhanaura, Amroha",
  "Maharana Institute of Professional Studies, Kanpur",
  "Maharana Institute of Technology & Sciences, Lucknow",
  "Maharana Prataap College of Engineering, Kanpur",
  "Maharana Pratap College of Pharmaceutical Sciences, Kanpur",
  "Maharana Pratap College of Pharmacy, Kanpur",
  "Maharana Pratap Engineering College, Kanpur",
  "Maharishi Institute of Management, Greater Noida",
  "Mahatma Gandhi Institute of Pharmacy, Lucknow",
  "Mahatma Gandhi Mission College of Engineering & Technology, Noida",
  "Mahatma Gandhi Universe Institute, Unnao",
  "Mahaveer College of Pharmacy, Meerut",
  "Mahaveer Institute of Engineering and Technology, Meerut",
  "Mahaveer Institute of Technology and Management, Raebareli",
  "Mahaveer Institute of Technology, Sardhana Road, Meerut",
  "Malti Memorial Trusts CSM \"group of Institutions\", Faculty of B. Pharmacy, Allahabad",
  "Mangalmay Institute of Engineering & Technology, Greater Noida",
  "Mangalmay Institute of Engineering and Technology, Knowledge Park, Greater Noida",
  "Marathwada Institute of Technology, Bulandshahr",
  "Mascot Institute of Management, Bareilly",
  "Meerut Institute of Engineering and Technology",
  "Meerut Institute of Technology, Baral, Partapur",
  "Meerut International Institute of Technology",
  "Mesco Institute of Pharmacy, Amroha",
  "Metro College of Health Sciences & Research, Greater Noida",
  "Modern Institute of Technology and Management, Duhai, Ghaziabad",
  "Moradabad Educational Trust (MET) Group of Institutions, Faculty of B. Architecture",
  "Moradabad Educational Trust (MET) Group of Institutions, Faculty of Pharmacy",
  "Moradabad Institute of Technology",
  "Motilal Rastogi School of Management, Lucknow",
  "NARAINA SCHOOL OF PLANNING & ARCHITECTURE, Kanpur",
  "NIMT Institute of Hospital & Pharma Management, Greater Noida",
  "NKBR College of Pharmacy & Research Centre, Meerut",
  "NSS College of Management, Mathura",
  "Nandani Nagar Mahavidayala College of Pharmacy, Gonda",
  "Nandini Nagar Technical Campus, Gonda",
  "Naraina College of Engineering & Technology, Kanpur",
  "Naraina Vidya Peeth Engineering & Management Institute, Kanpur",
  "Naraina Vidya Peeth Group of Institutions Faculty of Pharmacy, Kanpur",
  "Naraina Vidya Peeth Management Institute, Kanpur",
  "Narmadeshwar Management College, Lucknow",
  "Navneet College of Technology & Management, Azamgarh",
  "Neelam College of Engineering & Technology, Kirawali, Agra",
  "Neelkanth Institute of Technology, Pawli Khas, Modipuram, Meerut",
  "Nitra Technical Campus, Ghaziabad",
  "Noble Institute of Management & Technology, Lucknow",
  "Noida Institute of Engineering & Technology (MCA Institute), Greater Noida",
  "Noida Institute of Engineering and Technology, Greater Noida",
  "North India Institute of Technology, Najibabad",
  "Oxford College of Pharmacy, Mussori-Gulawati, NTPC Road, Ghaziabad",
  "PSIT COLLEGE OF MANAGEMENT, Kanpur",
  "PSIT College of Engineering, Kanpur",
  "Pahalwan Gurudeen College of Science and Technology, Lalitpur",
  "Panchwati Institute of Engineering & Technology, Delhi- Hardwar Bypass, Meerut",
  "Patronage Institute of Management Studies, Greater Noida",
  "Pharmacy College, Azamgarh",
  "Prabhat Engineering College, Kanpur Dehat",
  "Pranveer Singh Institute of Technology, Kanpur",
  "Prasad Institute of Technology, Jaunpur",
  "Pratap College of Management, Vill.Sindhav, Fatehpur",
  "Prayag Institute of Technology & Management, Allahabad",
  "Prem Prakash Gupta Institute of Engineering, Bareilly",
  "Prem Prakash Gupta Institute of Management, Bareilly",
  "Prince Institute of Innovative Technology, Greater Noida",
  "Purvanchal Institute of Architecture & Design, Gida, Gorakhpur",
  "R.D. Engineering College Research Center, Duhai, Ghaziabad",
  "R.D. Engineering College, Duhai, Ghaziabad",
  "R.D. Foundations Group of Institutions, Faculty of Engineering, Kadrabad, Modinagar",
  "R.K Pharmacy College, Azamgarh",
  "R.K. College of Pharmacy, Moradabad",
  "R.R. Institute of Modern Technology, Lucknow",
  "R.S.D. Academy, College of Management & Technology, Moradabad",
  "R.V. Institute of Technology, Bijnor",
  "R.V. Northland Institute of Management, Dadri",
  "R.V. Northland Institute, Dadri",
  "RADHA KRISHNA COLLEGE OF PHARMACY, Kanpur",
  "RAHUL SANKRITYAYAN COLLEGE OF PHARMACY, Azamgarh",
  "RAMDENI SINGH JAGDISH SINGH MEMORIAL SAMITI, BAGHAWER, AZAMGARH, Azamgarh",
  "RD Foundation's Group of Institutions, Faculty of Management, Modinagar",
  "RDS College of Pharmacy, Jaunpur",
  "Radha Govind Group of Institutions, Meerut",
  "Radha Govind Institute of Pharmacy, Moradabad-Chandausi Road",
  "Raj Kumar Goel Institute of Technology & Management, Ghaziabad",
  "Raj Kumar Goel Institute of Technology, Ghaziabad",
  "Raj School of Management & Sciences, Varanasi",
  "Raja Balwant Singh Engineering Technical Campus, Agra",
  "Raja Balwant Singh Management Technical Campus, Agra",
  "Rajarshi Rananjay Singh College of Pharmacy, Amethi",
  "Rajarshi Rananjay Singh College of Pharmacy, Sultanpur",
  "Rajarshi Rananjay Singh Institute of Management & Technology, Amethi",
  "Rajarshi Rananjay Singh Institute of Management & Technology, Sultanpur",
  "Rajarshi School of Management and Technology (RSMT), Varanasi",
  "Rajeev Academy for Pharmacy, Mathura",
  "Rajeev Academy for Technology & Management, Mathura",
  "Rajeev Gandhi College of Pharmacy, Maharajganj",
  "Rajendra Prasad College of Management, Azamgarh",
  "Rajkiya Engineering College, Ambedkar Nagar, Akbarpur",
  "Rajkiya Engineering College, Azamgarh",
  "Rajkiya Engineering College, Banda",
  "Rajkiya Engineering College, Bijnor",
  "Rajkiya Engineering College, Kannauj",
  "Rajkiya Engineering College, Mainpuri",
  "Rajkiya Engineering College, Sonbhadra",
  "Rajshree Institute of Management & Technology, Bareilly",
  "Rakshpal Bahadur College of Engineering & Technology, Bareilly",
  "Rakshpal Bahadur College of Pharmacy, Bareilly",
  "Rakshpal Bahadur Management Institute, Bareilly",
  "Rakshpal Bahadur Management Institute, Greater Noida",
  "Ram Chameli Chaddha Vishwas Girls College, Ghaziabad",
  "Ram-Eesh Institute of Vocational and Technical Education, Greater Noida",
  "Rameshwaram Institute of Technology & Management, Lucknow",
  "Remote Sensing Application Centre, Lucknow",
  "Rishi Chadha Vishvas Girls Institute of Technology for Women, Ghaziabad",
  "Rishi Institute of Engineering & Technology, Partapur, Meerut",
  "Rudra Group of Institutions, Meerut",
  "S P Memorial Institute of Technology, Kaushambi",
  "S S Institute of Management, Lucknow",
  "S.D. College of Pharmacy & Vocational Studies, Muzaffarnagar",
  "S.D.College of Engineering and Technology, Muzaffarnagar",
  "S.D.College of Management Studies, Bhopa Road, Muzaffarnagar",
  "S.R. INSTITUTE OF PHARMACY, Bareilly",
  "S.R. Institute of Management & Technology, Lucknow",
  "S.T.E.P.- H.B.T.I., Kanpur",
  "SARAS COLLEGE OF PHARMACY, Baghpat",
  "SIGNA COLLEGE OF PHARMACY, Kanpur",
  "SR Group of Institutions College of Engineering Management & Technology, Jhansi",
  "SR Group of Institutions College of Pharmacy, Jhansi",
  "SR Group of Institutions College of Science and Engineering, Jhansi",
  "SRM Business School, Lucknow",
  "SSLD Varshney Engineering College, Aligarh - Kanpur G.T. Road",
  "SSLD Varshney Institute of Management & Engineering, Aligarh",
  "STELLER INSTITUTE OF PHARMACY, Bareilly",
  "SVS Group of Institutions, Meerut",
  "Sachdeva Institute of Technology, Mathura",
  "Sacred Heart Institute of Management & Technology, Sitapur",
  "Sagar Institute of Technology & Management Department of Pharmacy, Barabanki",
  "Sagar Institute of Technology & Management, Barabanki",
  "Saharanpur Institute of Advance Studies, Gokelpur",
  "Saharanpur Pharmacy College",
  "Samrat Ashok Rajkiya Engineering College, Mirzapur",
  "Sanjay College of Pharmacy, Mathura",
  "Sanskar College of Architecture & Planning, Ghaziabad",
  "Sanskar College of Engineering & Technology, Ghaziabad",
  "Sanskar College of Management & Computer Application, Allahabad",
  "Sanskar College of Pharmacy & Research, Ghaziabad",
  "Sanskriti College of Higher Education and Studies, Kanpur Dehat",
  "Saraswati Higher Education & Technical College of Engineering, Varanasi",
  "Saraswati Higher Education & Technical College of Pharmacy, Varanasi",
  "Saraswati Institute of Engineering & Technology, Pilkhuwa, Hapur",
  "Sardar Bhagat Singh College of Technology & Management, Lucknow",
  "Saroj Institute of Management & Technology, Lucknow",
  "Saroj Institute of Technology & Management, Lucknow",
  "Sarvottam Institute of Technology & Management, Greater Noida",
  "Satyadeo College of Pharmacy, Ghazipur",
  "School of Business Management and Technology, Khurja Road, Bulandshahr",
  "School of Management Science (SMS Institute of Technology), Lucknow",
  "School of Management Sciences, Varanasi",
  "Seth Sri Nivas Agarwal Institute of Management, Kanpur",
  "Seth Sriniwas Agarwal Institute of Engineering and Technology, Kanpur",
  "Seth Vishambhar Nath Institute of Engineering & Technology, Barabanki",
  "Seth Vishambhar Nath Institute of Management Studies & Research, Barabanki",
  "Seth Vishambhar Nath Institute of Pharmaceutical Sciences, Barabanki",
  "Seth Vishambhar Nath Institute of Pharmacy, Barabanki",
  "Shakti College of Pharmacy, Dulhinpur, Balrampur",
  "Shambhunath Institute of Engg. & Technology, Allahabad",
  "Shambhunath Institute of Management, Allahabad",
  "Shambhunath Institute of Pharmacy, Allahabad",
  "Shanti Institute of Technology, Kurali, Baghpat Road, Meerut",
  "Shanti Niketan Trust's Group of Institutions, Faculty of Management, Mohiuddinpur, Meerut",
  "Sherwood College of Engineering Research & Technology, Barabanki",
  "Sherwood College of Management, Lucknow",
  "Sherwood College of Pharmacy, Barabanki",
  "Shine College of Management, Lucknow",
  "Shiv Bali Singh Group of Educational and Training Institute College of Pharmacy, Fatehpur",
  "Shivadan Singh Institute of Technology and Management, Aligarh",
  "Shree Jee Baba Institute of Professional Studies, Semari Chata, Mathura",
  "Shree Jee Goverdhan Maharaj College of Professional Studies, Mathura",
  "Shree Satya Institute of Management, Lodhipur Rajput, Palbara, Moradabad",
  "Shri Giriraj Maharaj Institute of Management, Mundesi Kosi Khurd, Mathura",
  "Shri Gopichand College of Pharmacy, Baghpat",
  "Shri Jeet Ram Smarak Institute of Engg. and Technology, Bareilly",
  "Shri Krishan College of Engineering, Singhawali Ahir, Baghpat",
  "Shri Nath Ji Institute for Technical Education, VIll-Ghat, Delhi- Roorkee Bypass, Meerut",
  "Shri R.L.T. Institute of Pharmaceutical Science & Technology, Etawah",
  "Shri RLT Institute of Management, Etawah",
  "Shri Ram College of Pharmacy, Muzaffarnagar",
  "Shri Ram Group of Colleges, Muzaffarnagar",
  "Shri Ram Murti Smarak College of Engineering & Technology, Bareilly",
  "Shri Ram Murti Smarak College of Engineering, Technology & Research, Bareilly",
  "Shri Rammurti Smarak College of Engineering & Technology, Unnao",
  "Shri Ramswaroop College of Engineering & Management, Lucknow",
  "Shri Rawatpura Sarkar Institute of Pharmacy, Jhansi",
  "Shri Siddhi Vinayak Institute of Management, Bareilly",
  "Shri Siddhi Vinayak Institute of Technology, Bareilly",
  "Sir Madan Lal Institute of Management, Etawah",
  "Sky Line Institute of Management & Technology, Greater Noida",
  "Sky line Institute of Engineering & Technology, Greater Noida",
  "Skyline Institute of Pharmacy, Greater Noida",
  "Smt. Vidyawati College of Pharmacy, Jhansi",
  "Smt.Fulehra Smarak College of Pharmacy, Ballia",
  "Society of Advanced Management Studies, Institute of Hotel Management, Varanasi",
  "Spectrum Institute of Pharmaceutical Science & Research, Greater Noida",
  "Srajan Institute of Management & Technology, Bareilly",
  "Sri Madan Lal Institute of Pharmacy, Etawah",
  "Sri Ram College of Management, Muzaffarnagar",
  "Sri Sharda Institute Of Management and Technology, Lucknow",
  "Sri Sri Institute of Technology & Management, Kasganj",
  "Sun Institute of Management and Technology, Shahjahanpur",
  "Sunder Deep College of Architecture, Dasna, Ghaziabad",
  "Sunder Deep College of Hotel Management, Dasna, Ghaziabad",
  "Sunderdeep Engineering College, Dasna, Ghaziabad",
  "Sunderdeep Pharmacy College, Dasna, Ghaziabad",
  "Sunrise Institute of Engineering Technology & Management, Unnao",
  "Suyash Institute of Information Technology, Gorakhpur",
  "T.D.L. College of Technology & Management, Lucknow",
  "TRC MAHAVIDYALAYA, DEPARTMENT OF PHARMACY, Barabanki",
  "Technical Education & Research Institute, Ghazipur",
  "Translam Institute of Pharmaceutical Education & Research, Rajpura, Mawana Road, Meerut",
  "Translam Institute of Technology & Management, Mawana Road, Meerut",
  "Trivedi Institute of Management & Technology, Fatehpur",
  "U.P. Institute of Design, Noida",
  "Unique Institute of Management & Technology, Modinagar",
  "United College of Engineering & Management, Allahabad",
  "United College of Engineering & Research, Allahabad",
  "United College of Engineering and Research, Greater Noida",
  "United Institute of Management, Allahabad",
  "United Institute of Management, Greater Noida",
  "United Institute of Pharmacy, United College of Engg. & Research, Allahabad",
  "United Institute of Technology, Allahabad",
  "Unnati Management College, Daulatpur, Farah, Mathura",
  "Utkarsh College of Management Education, Bareilly",
  "Uttam Institute of Management Studies, Runakta, Kirawali Road, Agra",
  "Uttar Pradesh Textile Technology Institute, Kanpur",
  "V.Tech Institute Of Integrated Technology, Bulandshahr",
  "VISION INSTITUTE OF MANAGEMENT, Kanpur",
  "Vedant Institute of Management & Technology, Garhmukteshwar",
  "Veer Kunwar Institute of Technology, Bijnor",
  "Veer Vijay Pharmacy College, Saharanpur",
  "Vidya College of Engineering, Meerut",
  "Vidya Institute of Fashion Technology, Baghpat Road, Meerut",
  "Vidya School of Business, Meerut",
  "Vinayak Vidyapeeth, Pawli khas, Modipuram, Meerut",
  "Vindhya Gurukul College of Pharmacy, Mirzapur",
  "Vishveshwarya College of Education, Mawana, Meerut",
  "Vishveshwarya Group of Institutions, Dadri",
  "Vishveshwarya Institute of Technology, Dadri",
  "Vision Institute of Technology, Kanpur",
  "Vision Institute of Technology, Shahpur Madrak, Aligarh",
  "Vivek College of Management & Technology, Bijnor",
  "Vivek College of Technical Education, Bijnor",
  "Vivekanand College of Technology & Management, Near Khair Road, Aligarh",
  "Viveknanad Institute of Technology & Science, Jindal Nagar, Ghaziabad",
  "YASH RAJ INSTITUTE OF PHARMACY, Lucknow",
  "Yogendra Nath Saxena College of Pharmacy & Research, Amroha",
  "tahira institute of medical sciences, Gorakhpur",
  "Other / Unlisted Affiliated College"
]

export const UP_DISTRICTS = [
  "Agra",
  "Aligarh",
  "Ambedkar Nagar",
  "Amethi",
  "Amroha",
  "Auraiya",
  "Ayodhya",
  "Azamgarh",
  "Baghpat",
  "Bahraich",
  "Ballia",
  "Balrampur",
  "Banda",
  "Barabanki",
  "Bareilly",
  "Basti",
  "Bhadohi",
  "Bijnor",
  "Budaun",
  "Bulandshahr",
  "Chandauli",
  "Chitrakoot",
  "Deoria",
  "Etah",
  "Etawah",
  "Farrukhabad",
  "Fatehpur",
  "Firozabad",
  "Gautam Buddha Nagar (Noida/Greater Noida)",
  "Ghaziabad",
  "Ghazipur",
  "Gonda",
  "Gorakhpur",
  "Hamirpur",
  "Hapur",
  "Hardoi",
  "Hathras",
  "Jalaun",
  "Jaunpur",
  "Jhansi",
  "Kannauj",
  "Kanpur Dehat",
  "Kanpur Nagar",
  "Kasganj",
  "Kaushambi",
  "Kheri",
  "Kushinagar",
  "Lalitpur",
  "Lucknow",
  "Maharajganj",
  "Mahoba",
  "Mainpuri",
  "Mathura",
  "Mau",
  "Meerut",
  "Mirzapur",
  "Moradabad",
  "Muzaffarnagar",
  "Pilibhit",
  "Pratapgarh",
  "Prayagraj (Allahabad)",
  "Raebareli",
  "Rampur",
  "Saharanpur",
  "Sambhal",
  "Sant Kabir Nagar",
  "Shahjahanpur",
  "Shamli",
  "Shravasti",
  "Siddharthnagar",
  "Sitapur",
  "Sonbhadra",
  "Sultanpur",
  "Unnao",
  "Varanasi",
];
